const data = [
  {
    id: 1,
    title: "Idli",
    category: "Breakfast",
    type: "Veg",
    price: 40,
    rating: 4.8,
    bestSeller: true,
    image: "https://images.pexels.com/photos/36854501/pexels-photo-36854501.jpeg"
  },
  {
    id: 2,
    title: "Dosa",
    category: "Breakfast",
    type: "Veg",
    price: 60,
    rating: 4.7,
    bestSeller: false,
    image: "https://images.pexels.com/photos/20422129/pexels-photo-20422129.jpeg",
  },
  {
    id: 3,
    title: "Egg Omelette",
    category: "Breakfast",
    type: "Non-Veg",
    price: 70,
    rating: 4.6,
    bestSeller: true,
    image: "https://images.pexels.com/photos/27396342/pexels-photo-27396342.jpeg",
  },
  {
    id: 4,
    title: "Chicken Sandwich",
    category: "Breakfast",
    type: "Non-Veg",
    price: 90,
    rating: 4.5,
    bestSeller: false,
    image: "https://images.pexels.com/photos/29177425/pexels-photo-29177425.jpeg",
  },
  {
    id: 5,
    title: "Veg Meals",
    category: "Lunch",
    type: "Veg",
    price: 120,
    rating: 4.9,
    bestSeller: true,
    image: "https://images.pexels.com/photos/12737914/pexels-photo-12737914.jpeg",
  },
  {
    id: 6,
    title: "Paneer Biryani",
    category: "Lunch",
    type: "Veg",
    price: 180,
    rating: 4.8,
    bestSeller: false,
    image: "https://images.pexels.com/photos/9609859/pexels-photo-9609859.jpeg",
  },
  {
    id: 7,
    title: "Chicken Biryani",
    category: "Lunch",
    type: "Non-Veg",
    price: 220,
    rating: 4.9,
    bestSeller: true,
    image: "https://images.pexels.com/photos/20642812/pexels-photo-20642812.jpeg",
  },
  {
    id: 8,
    title: "Fish Curry",
    category: "Lunch",
    type: "Non-Veg",
    price: 250,
    rating: 4.7,
    bestSeller: false,
    image: "https://images.pexels.com/photos/5410403/pexels-photo-5410403.jpeg",
  },
  {
    id: 9,
    title: "Paneer Curry",
    category: "Dinner",
    type: "Veg",
    price: 180,
    rating: 4.8,
    bestSeller: true,
    image: "https://images.pexels.com/photos/9609838/pexels-photo-9609838.jpeg",
  },
  {
    id: 10,
    title: "Roti",
    category: "Dinner",
    type: "Veg",
    price: 40,
    rating: 4.4,
    bestSeller: false,
    image: "https://images.pexels.com/photos/12427834/pexels-photo-12427834.jpeg",
  },
  {
    id: 11,
    title: "Chicken Curry",
    category: "Dinner",
    type: "Non-Veg",
    price: 250,
    rating: 4.8,
    bestSeller: true,
    image: "https://images.pexels.com/photos/35629938/pexels-photo-35629938.jpeg",
  },
  {
    id: 12,
    title: "Mutton Curry",
    category: "Dinner",
    type: "Non-Veg",
    price: 320,
    rating: 4.9,
    bestSeller: true,
    image: "https://images.pexels.com/photos/9609846/pexels-photo-9609846.jpeg",
  },
];

export default data;